// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGJBpDZMTpu_AJhziVKkzEtKq4D_KaiaM',
    appId: '1:510531605368:android:2026b17e88cd35e9f2ae8d',
    messagingSenderId: '510531605368',
    projectId: 'bookstash-3b5de',
    storageBucket: 'bookstash-3b5de.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfebFVsJAnL-N5EpfOOFaVNXLSRp6MsSM',
    appId: '1:510531605368:web:86acb905c101f323f2ae8d',
    messagingSenderId: '510531605368',
    projectId: 'bookstash-3b5de',
    authDomain: 'bookstash-3b5de.firebaseapp.com',
    storageBucket: 'bookstash-3b5de.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFok1ynW5Cei6_BBxP-bNmypnUEV3NQXw',
    appId: '1:510531605368:ios:c6d1248f2ee709b6f2ae8d',
    messagingSenderId: '510531605368',
    projectId: 'bookstash-3b5de',
    storageBucket: 'bookstash-3b5de.firebasestorage.app',
    iosClientId: '510531605368-9eipbbgnh7qsqlhbu2dpe40ovr56e17h.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFok1ynW5Cei6_BBxP-bNmypnUEV3NQXw',
    appId: '1:510531605368:ios:c6d1248f2ee709b6f2ae8d',
    messagingSenderId: '510531605368',
    projectId: 'bookstash-3b5de',
    storageBucket: 'bookstash-3b5de.firebasestorage.app',
    iosClientId: '510531605368-9eipbbgnh7qsqlhbu2dpe40ovr56e17h.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfebFVsJAnL-N5EpfOOFaVNXLSRp6MsSM',
    appId: '1:510531605368:web:d5d69d78a4f516c1f2ae8d',
    messagingSenderId: '510531605368',
    projectId: 'bookstash-3b5de',
    authDomain: 'bookstash-3b5de.firebaseapp.com',
    storageBucket: 'bookstash-3b5de.firebasestorage.app',
  );

}